-- 4. WORKSHOPS TABLE
CREATE TABLE IF NOT EXISTS "workshops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "trainer_id" INT,
  "mentor_name" VARCHAR(255),
  "location" VARCHAR(255),
  "start_date" DATE,
  "end_date" DATE,
  "start_time" TIME,
  "end_time" TIME,
  "capacity" INT,
  "enrolled_count" INT DEFAULT 0,
  "status" VARCHAR(50) DEFAULT 'scheduled',
  "schedule" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. WORKSHOP_ATTENDANCE (الجدول القديم اللي السيدر مستنيه)
CREATE TABLE IF NOT EXISTS "workshop_attendance" (
  "workshop_id" INT,
  "user_id" INT,
  "attended_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "feedback" TEXT,
  FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

-- 6. WORKSHOP_ENROLLMENTS
CREATE TABLE IF NOT EXISTS "workshop_enrollments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" INT NOT NULL,
  "entrepreneur_id" INT,
  "entrepreneur_name" VARCHAR(255),
  "entrepreneur_email" VARCHAR(255),
  "enrollment_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "attended" BOOLEAN DEFAULT FALSE,
  "feedback_rating" INT,
  "feedback_comment" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id") ON DELETE CASCADE
);

-- 7. WORKSHOP_FEEDBACK
CREATE TABLE IF NOT EXISTS "workshop_feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" INT NOT NULL,
  "enrollment_id" INT,
  "rating" INT,
  "comment" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("enrollment_id") REFERENCES "workshop_enrollments" ("id") ON DELETE CASCADE
);

-- Add index for better query performance
CREATE INDEX IF NOT EXISTS idx_workshop_enrollments_workshop_id ON workshop_enrollments(workshop_id);
CREATE INDEX IF NOT EXISTS idx_workshop_feedback_workshop_id ON workshop_feedback(workshop_id);
CREATE INDEX IF NOT EXISTS idx_workshop_attendance_workshop ON workshop_attendance(workshop_id);