-- Migration: Create Projects Schema (From Scratch)
CREATE TABLE IF NOT EXISTS "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "domain" VARCHAR(255),
  "short_description" VARCHAR(150),
  "problem" TEXT,
  "solution" TEXT,
  "tech_stack" VARCHAR(500),
  "stage" VARCHAR(50) DEFAULT 'idea',
  "status" VARCHAR(50) DEFAULT 'in-progress',
  "github_url" VARCHAR(500),
  "demo_url" VARCHAR(500),
  "team_type" VARCHAR(50),
  "looking_for_cofounders" BOOLEAN DEFAULT FALSE,
  "funding_stage" VARCHAR(50),
  "approved" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. PROJECT_ENTREPRENEURS TABLE
CREATE TABLE IF NOT EXISTS "project_entrepreneurs" (
  "project_id" INT,
  "user_id" INT,
  "role_in_project" VARCHAR(50),
  FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE,
  PRIMARY KEY ("project_id", "user_id")
);

-- Create resources table
CREATE TABLE IF NOT EXISTS "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "type" VARCHAR(50),
  "description" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create project_resources junction table
CREATE TABLE IF NOT EXISTS "project_resources" (
  "project_id" INT NOT NULL,
  "resource_id" INT NOT NULL,
  "allocated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("resource_id") REFERENCES "resources" ("id") ON DELETE CASCADE,
  PRIMARY KEY ("project_id", "resource_id")
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_projects_domain ON "projects"("domain");
CREATE INDEX IF NOT EXISTS idx_projects_stage ON "projects"("stage");
CREATE INDEX IF NOT EXISTS idx_projects_team_type ON "projects"("team_type");
CREATE INDEX IF NOT EXISTS idx_projects_funding_stage ON "projects"("funding_stage");