-- Drop table if exists to ensure clean state
DROP TABLE IF EXISTS "funding_requests" CASCADE;

-- Create funding_requests table with enhanced fields for admin review
CREATE TABLE IF NOT EXISTS "funding_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" INT,
  "investor_id" INT,
  "amount" DECIMAL(15,2),
  "status" VARCHAR(50) DEFAULT 'Pending',
  "funding_stage" VARCHAR(50),
  "description" TEXT,
  "reviewed_by" INT,
  "notes" TEXT,
  "reviewed_at" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE,
  FOREIGN KEY ("investor_id") REFERENCES "users" ("id") ON DELETE SET NULL,
  FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

-- Create indexes for better query performance
CREATE INDEX idx_funding_project ON "funding_requests"("project_id");
CREATE INDEX idx_funding_status ON "funding_requests"("status");
CREATE INDEX idx_funding_stage ON "funding_requests"("funding_stage");
CREATE INDEX idx_funding_created ON "funding_requests"("created_at");
