CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "user_code" varchar(255) UNIQUE,
  "email" varchar(255) UNIQUE,
  "password" varchar(255),
  "role" varchar(50) DEFAULT 'entrepreneur',
  "profile_image" varchar(255),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "domain" varchar(100),
  "stage" varchar(50) DEFAULT 'Idea',
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_entrepreneurs" (
  "project_id" int,
  "user_id" int,
  "role_in_project" varchar(50)
);

CREATE TABLE "workshops" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "trainer_id" int,
  "schedule" timestamp,
  "capacity" int,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "workshop_attendance" (
  "workshop_id" int,
  "user_id" int,
  "attended_at" timestamp DEFAULT (now()),
  "feedback" text
);

CREATE TABLE "resources" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "type" varchar(50),
  "description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "project_resources" (
  "project_id" int,
  "resource_id" int,
  "allocated_at" timestamp DEFAULT (now())
);

CREATE TABLE "funding_requests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" int,
  "investor_id" int,
  "amount" decimal(15,2),
  "status" varchar(50) DEFAULT 'Pending',
  "created_at" timestamp DEFAULT (now())
);


CREATE TABLE IF NOT EXISTS "session" (
  "sid" VARCHAR NOT NULL COLLATE "default",
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("sid")
);





ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid");

ALTER TABLE "project_entrepreneurs" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_entrepreneurs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "workshops" ADD FOREIGN KEY ("trainer_id") REFERENCES "users" ("id");

ALTER TABLE "workshop_attendance" ADD FOREIGN KEY ("workshop_id") REFERENCES "workshops" ("id");

ALTER TABLE "workshop_attendance" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_resources" ADD FOREIGN KEY ("resource_id") REFERENCES "resources" ("id");

ALTER TABLE "funding_requests" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "funding_requests" ADD FOREIGN KEY ("investor_id") REFERENCES "users" ("id");
